all:
  vars:
    ip_master: 192.168.1.220
  children:
    master:
      hosts:
        kmaster:
          ansible_host: 192.168.1.220
    nodes:
      hosts:
        node1:
          ansible_host: 192.168.1.221
        node2:
          ansible_host: 192.168.1.222
        node3:
          ansible_host: 192.168.1.223
