- name: ajout du hostname dans /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ansible_default_ipv4.address }}.+$"
    line: "{{ ansible_default_ipv4.address }} {{ ansible_hostname }}"

- name: ajout des cgroups dans /boot/cmdline.txt
  template:
    src: cmdline.txt.j2
    dest: /boot/cmdline.txt
    owner: root
    group: root
    mode: 0755

- name: désactivation du swap
  shell: dphys-swapfile swapoff && dphys-swapfile uninstall && update-rc.d dphys-swapfile remove
  ignore_errors: True

# pas suffisant quant la machine redémarre le swap est actif
#- name: swapoff
#  shell: swapoff -a
- name: suppression paquet dphys-swapfile
  apt:
    name:
      - dphys-swapfile
    purge: yes
    autoremove: yes
    state: absent


- name: vérification si docker existe
  stat:
    path: /usr/bin/docker
  register: docker_exist
  ignore_errors: True

- name: Téléchargement paquet docker
  get_url:
    url: "{{ item }}"
    dest: /tmp
  with_items:
    - "https://download.docker.com/linux/debian/dists/buster/pool/stable/armhf/containerd.io_1.2.6-3_armhf.deb"
    - "https://download.docker.com/linux/debian/dists/buster/pool/stable/armhf/docker-ce-cli_18.09.7~3-0~debian-buster_armhf.deb"
    - "https://download.docker.com/linux/debian/dists/buster/pool/stable/armhf/docker-ce_18.09.7~3-0~debian-buster_armhf.deb"
  when: docker_exist.stat.exists == False

- name: install .deb using dpkg
  apt:
    deb: "{{ item }}"
    state: present
  with_items:
    - /tmp/containerd.io_1.2.6-3_armhf.deb
    - /tmp/docker-ce-cli_18.09.7~3-0~debian-buster_armhf.deb
    - /tmp/docker-ce_18.09.7~3-0~debian-buster_armhf.deb
  when: docker_exist.stat.exists == False

- name: ansible add pi to group docker
  user:
    name: pi
    groups: docker

- name: changement de conf pour les bridges
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present

- name: configuration cgroupdriver
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644

- name: Création dossier /etc/systemd/system/docker.service.d
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: 0775

- name: redémarrage docker
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker

- name: installation de apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: ajout dépôt kub - key
  shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
  args:
    warn: no

- name: ajout dépôt kub - source
  template:
    src: kubernetes.list.j2
    dest: /etc/apt/sources.list.d/kubernetes.list
    owner: root
    group: root
    mode: 0644

- name: apt-get update
  apt:
    update_cache: yes

- name: installation des paquets kubernetes
  apt:
    name:
    - "kubelet"
    - "kubeadm"
    - "kubectl"
    - "kubernetes-cni"
    state: present
    force: yes
